let root = new Vue({
    el:'#root',
    data:{
        columnData:[
            {
                title:'姓名',
                key:'name',
            },
            {
                title:'年龄',
                key:'age',
                sortable:true
            },
            {
                title:'出生日期',
                key:'birth',
                sortable:true
            },
            {
                title:'地址',
                key:'address'
            }
        ],
        tableData:[
            {
                name:'王小明',
                age:18,
                birth:'1999-09-21',
                address:'address1'
            },
            {
                name:'张小刚',
                age:25,
                birth:'1991-04-12',
                address:'address2'
            },
            {
                name:'李小红',
                age:20,
                birth:'1994-03-01',
                address:'address3'
            },
            {
                name:'周小微',
                age:21,
                birth:'1993-06-21',
                address:'address4'
            }
        ]
    }
})